package com.hospital.model;

public enum DepartmentType {
    CARDIOLOGY, ORTHOPEDICS, NEUROLOGY, PEDIATRICS,
    GYNECOLOGY, DERMATOLOGY, ENT, OPHTHALMOLOGY,
    PSYCHIATRY, GENERAL_MEDICINE, EMERGENCY, ICU
}